name: 'Setup Java and Maven'
description: 'Setup Java and Maven for pipeline'
inputs:
  github-token:
    description: 'Token used to reach maven.pkg.github.com'
    required: true
  java-version:
    description: 'Java SDK version to use'
    required: false
    default: '21'
  maven-version:
    description: 'Maven version to use'
    required: false
    default: '3.9.5'
runs:
  using: "composite"
  steps:
    - name: Create maven .m2 settings
      uses: whelk-io/maven-settings-xml-action@9dc09b23833fa9aa7f27b63db287951856f3433d # ratchet:whelk-io/maven-settings-xml-action@v22
      with:
        repositories: '[{"id": "github", "name": "github", "url": "https://maven.pkg.github.com/${{ github.repository }}/", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" }}]'
        servers: '[{ "id": "github", "username": "${{ github.actor }}", "password": "${{ inputs.github-token }}" }]'
        output_file: 'settings.xml'
    - name: Set up JDK-${{ inputs.java-version }} with cache
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # ratchet:actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # ratchet:stCarolas/setup-maven@v5
      with:
        maven-version: ${{ inputs.maven-version }}
