name: version-from-file
author: navjostein
description: Extract openapi version number from the file.
inputs:
  openapiFilePath:
    description: path to openapi.json file to read from
    required: true
outputs:
  openapiVersion:
    description: Extracted version number
    value: ${{ steps.openapi-version.outputs.openapiVersion }}
runs:
  using: 'composite'
  steps:
    - name: Openapi version
      id: openapi-version
      shell: bash
      # extract version number from generated openapi.json
      run: |
        echo "openapiVersion=$(jq --exit-status --raw-output '.info.version | capture("^(?<major>\\d+)\\.(?<minor>\\d+)$") | .major + "." + .minor' ${{ inputs.openapiFilePath }} || echo 'FEIL')" >> $GITHUB_OUTPUT
    - name: Feilsjekk OPENAPI_VERSION
      if: "${{ env.OPENAPI_VERSION == 'FEIL'}}"
      env:
        OPENAPI_VERSION: "${{ steps.openapi-version.outputs.openapiVersion }}"
      uses: actions/github-script@v8
      with:
        script: |
          core.setFailed('fant ikkje korrekt openapi version frå ${{ inputs.openapiFileName }}')