name: "Build and push docker image"
description: "Build and push docker image"
inputs:
  build-version:
    description: "Image tag for the docker image"
    required: true
  project_id:
    required: true
    description: "NAIS project id"
  identity_provider:
    required: true
    description: "NAIS identity provider"
  namespace:
    required: false
    description: "NAV team"
    default: "k9saksbehandling"
  push-image:
    required: false
    description: "Push the docker image (true|false)"
    default: "false"
  upload-image:
    required: false
    description: "upload the docker image to job (true|false)"
    default: "false"
  additional-tag:
    required: false
    description: "Additional labels to tag docker image with"
  dockerfile:
    description: "Dockerfile"
    required: true
    default: "Dockerfile"
  docker_context:
    description: "Docker context"
    required: false
    default: "."
  docker_platforms:
    description: "Docker platforms"
    required: false
  image_suffix:
    description: "Adds a suffix to the generated docker image name"
    required: false
    default: ""
  without_navikt_prefix:
    description: "Do not include navikt prefix in docker image name"
    required: false
    default: "false"
  image_base_name:
    description: "Use this as docker image name instead of github.repository name"
    required: false
    default: ""
  build-args:
    description: "List of build-time variables to pass on to docker/build-push-action"
    required: false
  labels:
    description: "List of labels to pass on to docker/metadata-action, for overwriting the defaults"
    required: false
outputs:
  image-artifact-name:
    description: 'artifact id of uploaded image'
    value: ${{ steps.image-artifact-name.outputs.image_artifact_name }}
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # ratchet:docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # ratchet:docker/setup-buildx-action@v2
    - name: NAIS login
      uses: nais/login@104bca34b70d1d00fe837bcd0689633978eca744 # ratchet:nais/login@v0
      id: login
      with:
        project_id: ${{ inputs.project_id }}
        identity_provider: ${{ inputs.identity_provider }}
        team: ${{ inputs.namespace }}
    - name: Setup environment
      shell: bash
      run: |
        if [ ! -f "${{ inputs.dockerfile }}" ]; then
          echo "::error ::Dockerfile not found: ${{ inputs.dockerfile }}. Do you need to prepend context or working directory?"
          exit 1
        elif [ ! -d "${{ inputs.docker_context }}" ]; then
          echo "::error ::Docker context not found: ${{ inputs.docker_context }}."
          exit 1
        fi
    - name: Generate docker image name
      id: docker_image_name
      shell: bash
      run: |
        image_name="${{ github.repository }}"
        image_base_name="${{ inputs.image_base_name }}"
        if [ "${{ inputs.without_navikt_prefix }}" == "true" ]; then
            image_name=$(echo ${{ github.repository }} | cut -d'/' -f2)
            # Overstyr til image_base_name input viss den er satt
            image_name="${image_base_name:-${image_name}}"
        elif [ ! -z "${{ inputs.image_base_name }}" ]; then
            repo_owner=$(echo ${{ github.repository }} | cut -d'/' -f1)
            image_name="${repo_owner}/${image_base_name}"
        fi
        
        echo "REPO_NAME=${{ steps.login.outputs.registry }}/${image_name}${{ inputs.image_suffix }}" >> $GITHUB_OUTPUT
    - name: Docker meta
      uses: docker/metadata-action@9dc751fe249ad99385a2583ee0d084c400eee04e # ratchet:docker/metadata-action@v4
      id: meta
      with:
        images: ${{ steps.docker_image_name.outputs.REPO_NAME}}
        tags: |
          type=raw,value=${{ inputs.build-version }}
          type=raw,value=${{ inputs.additional-tag }},enable=${{ inputs.additional-tag != null }}
          # set latest tag for default branch (master)
          type=raw,value=latest,enable={{is_default_branch}}
        labels: ${{ inputs.labels }}
    - name: Bygg og push docker image
      uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # ratchet:docker/build-push-action@v4
      id: build_push
      with:
        context: ${{ inputs.docker_context }}
        file: ${{ inputs.dockerfile }}
        build-args: ${{ inputs.build-args }}
        platforms: ${{ inputs.docker_platforms || 'linux/amd64,linux/arm64' }}
        pull: true
        push: ${{ inputs.push-image == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: ${{ (inputs.upload-image == 'true' && 'type=docker,dest=/tmp/local-docker-image.tar') || null }}
    - name: Generate SBOM, attest and sign image
      if: inputs.push-image == 'true'
      uses: nais/attest-sign@5e9450cc8a617286ca2d22859011e078ad1ef583 # ratchet:nais/attest-sign@v1
      with:
        image_ref: "${{ steps.docker_image_name.outputs.REPO_NAME}}@${{ steps.build_push.outputs.digest }}"
    - name: Upload image
      if: inputs.upload-image == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: local-docker-image
        path: /tmp/local-docker-image.tar
    - name: Set upload image artifact name
      id: image-artifact-name
      if: inputs.upload-image == 'true'
      shell: bash
      run: |
        echo "image_artifact_name=local-docker-image" >> $GITHUB_OUTPUT
