name: 'Send Slack Notification'
description: 'Sends test results to Slack'

inputs:
  webhook-url:
    description: 'Slack webhook URL'
    required: true
  test-results:
    description: 'JSON string containing test results'
    required: true

runs:
  using: "composite"
  steps:
    - name: Bygger opp slack melding
      shell: bash
      run: |
        beregning="${{ inputs.test-results.beregning || 'skipped' }}"
        pleiepengersamtidiguttak="${{ inputs.test-results.pleiepenger-samtidiguttak || 'skipped' }}"
        pleiepengerpleietrengende="${{ inputs.test-results.pleiepenger-pleietrengende || 'skipped' }}"
        pleiepengersoker="${{ inputs.test-results.pleiepenger-soker || 'skipped' }}"
        pleiepenger="${{ inputs.test-results.pleiepenger || 'skipped' }}"
        livetssluttfase="${{ inputs.test-results.livetssluttfase || 'skipped' }}"
        annet="${{ inputs.test-results.annet || 'skipped' }}"
        klage="${{ inputs.test-results.klage || 'skipped' }}"
        tilbake="${{ inputs.test-results.tilbake || 'skipped' }}"
        frontend="${{ inputs.test-results.frontend || 'skipped' }}"
        frontendlos="${{ inputs.test-results.frontend-los || 'skipped' }}"
        ung="${{ inputs.test-results.ung || 'skipped' }}"
        fordel="${{ inputs.test-results.fordel || 'skipped' }}"

        title="Verdikjede er "
        all_success=true

        test_results=("$beregning" "$pleiepengersamtidiguttak" "$pleiepengerpleietrengende" "$pleiepengersoker" "$pleiepenger" "$livetssluttfase" "$annet" "$frontend" "$klage" "$tilbake" "$frontendlos" "$ung" "$fordel")
        for result in "${test_results[@]}"; do
          if [[ "$result" != 'success' && "$result" != 'skipped' ]]; then
            all_success=false
            break
          fi
        done

        if [[ "$all_success" == true ]]; then
          title+="kjørt UTEN feil :rocket:"
        else
          title+="brukket :boom:"
        fi

        echo "SLACK_TITLE=$title" >> $GITHUB_ENV

        function echoStatus() {
          if [[ "$2" == 'success' ]]; then
            echo ":heavy_check_mark:  $1"
          elif [[ "$2" == 'skipped' ]]; then
            return
          else
            echo ":x:  $1"
          fi
        }

        echo 'SLACK_MESSAGE<<\n' >> $GITHUB_ENV
        echoStatus "Pleiepenger samtidig uttak" $pleiepengersamtidiguttak >> $GITHUB_ENV
        echoStatus "Pleiepenger pleietrengende" $pleiepengerpleietrengende >> $GITHUB_ENV
        echoStatus "Pleiepenger søker" $pleiepengersoker >> $GITHUB_ENV
        echoStatus "Beregning" $beregning >> $GITHUB_ENV
        echoStatus "Pleiepenger" $pleiepenger >> $GITHUB_ENV
        echoStatus "Livets sluttfase" $livetssluttfase >> $GITHUB_ENV
        echoStatus "Frontend" $frontend >> $GITHUB_ENV
        echoStatus "Omsorgspenger og annet" $annet >> $GITHUB_ENV
        echoStatus "Klage" $klage >> $GITHUB_ENV
        echoStatus "Tilbakekreving" $tilbake >> $GITHUB_ENV
        echoStatus "Frontend Los" $frontendlos >> $GITHUB_ENV
        echoStatus "Ungdomsytelsen" $ung >> $GITHUB_ENV
        echoStatus "Fordel" $fordel >> $GITHUB_ENV
        echo '*Actor*: ${{ github.actor }}' >> $GITHUB_ENV
        echo '*Trigger*: ${{ github.repository }}:${{ inputs.tag }}' >> $GITHUB_ENV
        echo '*Trigger action*: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Trigger action ${{ github.run_id }}>' >> $GITHUB_ENV
        echo '\n' >> $GITHUB_ENV
      # https://api.slack.com/block-kit
    - name: Slack message
      shell: bash
      run: |
        echo "${{ env.SLACK_TITLE }}"
        echo "${{ env.SLACK_MESSAGE }}"
    - name: Slack Notification
      shell: bash
      run: >
        curl -X POST
        -H 'Content-type: application/json'
        --data '{"blocks": [
          {
            "type": "header",
            "text": {"type": "plain_text", "text": "${{ env.SLACK_TITLE }}"}
          },
          {
            "type": "section",
            "text": {"type": "mrkdwn", "text": "${{ env.SLACK_MESSAGE }}"}
          }
        ]}'
        ${{ inputs.webhook-url }}