name: Build image
on:
  workflow_call:
    inputs:
      team:
        required: false
        type: string
        default: omsorgspenger
      dockercontext:
        required: false
        type: string
        default: .
      readertoken:
        required: false
        type: boolean
        default: false
    outputs:
      image:
        value: ${{ jobs.build.outputs.image }}

jobs:
  build:
    permissions:
      contents: read
      id-token: write # for nais/docker-build-push
    runs-on: ubuntu-latest
    outputs: 
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: gradle

      - name: Build shadowjar
        run: ./gradlew shadowjar
        env:
          GITHUB_TOKEN: ${{ (inputs.readertoken && secrets.READER_TOKEN) || secrets.GITHUB_TOKEN }}

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: ${{ inputs.team }}
          push_image: true
          pull: true
          dockerfile: Dockerfile
          docker_context: ${{ inputs.dockercontext }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
