name: Bygg og deploy
on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: main
      environment:
        required: false
        type: string
        default: gcp
      team:
        required: false
        type: string
        default: k9saksbehandling
      dockercontext:
        required: false
        type: string
        default: .
      readertoken:
        required: false
        type: boolean
        default: false

jobs:
  build:
    permissions:
      contents: read
      id-token: write # for nais/docker-build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: gradle

      - name: Build shadowjar
        run: ./gradlew shadowjar
        env:
          GITHUB_TOKEN: ${{ (inputs.readertoken && secrets.READER_TOKEN) || secrets.GITHUB_TOKEN }}

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: ${{ inputs.team }}
          push_image: true
          pull: true
          dockerfile: Dockerfile
          docker_context: ${{ inputs.dockercontext }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Deploy til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-${{ inputs.environment }}
          RESOURCE: nais/dev-${{ inputs.environment }}.yml
          IMAGE: ${{ steps.docker-push.outputs.image }}

      - name: Deploy til prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-${{ inputs.environment }}
          RESOURCE: nais/dev-${{ inputs.environment }}.yml
          IMAGE: ${{ steps.docker-push.outputs.image }}
