name: Generate openapi
description: Generate new openapi spec, and generate typescript from it.
inputs:
  readerToken:
    description: The secrets.READER_TOKEN allowing read of internal packages.
    required: true
  commitToken:
    description: Github token allowing commit on the repo.
    required: true
  openapiFilePath:
    description: What path to use for generated openapi.json file.
    required: true
    default: openapi.json
  dontCommit:
    description: If true, do not commit the generated openapi.json file.
    required: false
    default: "false"
outputs:
  openapiVersion:
    description: "generated openapi spec version"
    value: ${{ steps.openapi-version.outputs.openapiVersion }}
  openapiCommitted:
    description: "true if a new openapi file was commited"
    value: ${{ steps.change-commit.outputs.openapiCommitted }}

runs:
  using: 'composite'
  steps:
    - name: Setup java and maven
      uses: navikt/sif-gha-workflows/.github/actions/maven/setup-java-and-maven@main
      with:
        github-token: ${{ inputs.readerToken }}
        # Ved ny jdk versjon kan denne økes uten å vente på noe annet. (Kompileringsresultat fra denne action blir ikke brukt noe annet sted.)
        java-version: '25'
    - name: Maven install
      id: java-build
      uses: navikt/sif-gha-workflows/.github/actions/maven/test-and-build@main
      with:
        skip-tests: true
    - name: Openapi generate
      shell: bash
      run: mvn -s settings.xml exec:java --projects web
    - name: Openapi version
      id: openapi-version
      uses: navikt/sif-gha-workflows/.github/actions/openapi-version@openapi-next
      with:
        openapiFilePath: ${{ inputs.openapiFilePath }}
    # Commit and push any changes to openapi.json
    - name: Commit api endringer
      if: ${{ success() && inputs.dontCommit != 'true' }}
      id: change-commit
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.commitToken }}
        FILE_PATH: ${{ inputs.openapiFilePath }}
        DESTINATION_BRANCH: ${{ github.head_ref || github.ref_name }}
      run: |
        # Use git to detect changes, only commit and push if there are changes
        git add --force ${FILE_PATH}
        git diff --quiet --staged || 
        (
        export MESSAGE="$FILE_NAME updated by build pipeline"
        export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_PATH )
        gh api --method PUT /repos/:owner/:repo/contents/$FILE_PATH \
          --field message="$MESSAGE" \
          --field content=@<( base64 -i "${FILE_PATH}" ) \
          --field branch="$DESTINATION_BRANCH" \
          --field sha="$SHA" &&
        echo "openapiCommitted=true" >> $GITHUB_OUTPUT
        )
      # ^-Use the REST API to commit changes, so we get automatic commit signing

