name: Create or Update Git Tag
description: Creates or updates a Git tag for a specific commit based on the provided partial SHA in image_name. Automatically deletes the existing tag if it already exists, ensuring the tag always points to the desired commit.

inputs:
  sha:
    required: true
    description: "The full commit SHA"
  tag:
    required: true
    description: "Tag name for commit"
  github_token:
    required: true
    description: "Github token with contents:write"

runs:
  using: "composite"
  steps:
    - name: Tagg prodsatt commit
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const latestName = '${{ inputs.tag }}'
          const latestRef = 'tags/' + latestName
          const full_sha = '${{inputs.sha}}'

          // Delete existing tag if it exists
          try {
          await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: refName,
          });
          } catch (err) {
          if (err.status !== 404) throw err; // Ignore "not found" errors
          }

          console.log("lager tagg=" + latestName + " på commit " + full_sha)

          await github.rest.git.createRef({
          owner: context.repo.owner,
          repo: context.repo.repo,
          ref: 'refs/tags/' + latestName,
          sha: full_sha
          }).then((res) => {
          console.log("laget tagg=" + latestName)
          })
