name: Create or Update Git Tag
description: Creates or updates a Git tag for a specific commit. Automatically deletes the existing tag if it already exists, ensuring the tag is always unique.

inputs:
  sha:
    required: true
    description: "The full commit SHA"
  tag:
    required: true
    description: "Tag name for commit"
  github_token:
    required: true
    description: "Github token with contents:write"

runs:
  using: "composite"
  steps:
    - name: Tagg prodsatt commit
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const latestName = '${{ inputs.tag }}';
          const latestRef = 'tags/' + latestName;
          const full_sha = '${{inputs.sha}}';

          try {
            await github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: latestRef,
              sha: full_sha,
            });
            console.log("lager tagg=" + latestName + " på commit " + full_sha);
          } catch (updateError) {
            if (updateError.status === 422) {
              try {
                await github.rest.git.createRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: 'refs/tags/' + latestName,
                  sha: full_sha,
                });
                console.log("Tag fantes ikke fra før av. Oppretter " + latestName + " på commit " + full_sha);
              } catch (createError) {
                console.log("Feil ved oppretting av " + latestRef + ": ", createError);
                throw createError;
              }
            } else {
              console.log("Feil ved oppdatering av " + latestRef + ": ", updateError);
              throw updateError;
            }
          }
