name: Deploy image
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      environment:
        required: false
        type: string
        default: gcp
      deploy-prod:
        required: false
        type: boolean
        default: false
env:
  IMAGE: ${{ inputs.image }}
jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v6.0.3
      - name: Deploy til dev-${{ inputs.environment }}
        uses: nais/deploy/actions/deploy@157203210ef983b1d2fb32db50d177043ce95ebd # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-${{ inputs.environment }}
          RESOURCE: nais/naiserator.yaml
          VARS: nais/dev-${{ inputs.environment }}.json
      - name: Deploy til prod-${{ inputs.environment }}
        if: ${{ inputs.deploy-prod }}
        uses: nais/deploy/actions/deploy@157203210ef983b1d2fb32db50d177043ce95ebd # ratchet:nais/deploy/actions/deploy@v2
        env:
          RESOURCE: nais/naiserator.yaml
          CLUSTER: prod-${{ inputs.environment }}
          VARS: nais/prod-${{ inputs.environment }}.json
