name: Build
on:
  workflow_call:
    inputs:
      team:
        required: true
        type: string
        default: omsorgspenger
      dockercontext:
        required: false
        type: string
        default: .
      readertoken:
        required: false
        type: boolean
        default: false
      buildcommand:
        required: false
        type: string
        default: --configuration-cache build shadowjar -x test
      javaversion:
        required: false
        type: string
        default: '21'
      scan-sensitive-data:
        required: false
        type: boolean
        default: true
        description: "Skal sensitiv data scan kjøres?"
    outputs:
      image:
        value: ${{ jobs.build.outputs.image }}
jobs:
  sif-code-scan:
    if: ${{ inputs.scan-sensitive-data }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
      - uses: navikt/sif-gha-workflows/.github/actions/sif-code-scan@main
  build:
    permissions:
      contents: write # for dependency submission
      id-token: write # for nais/docker-build-push
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
      - uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # ratchet:gradle/actions/wrapper-validation@v6.1.0
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # ratchet:actions/setup-java@v5.2.0
        with:
          java-version: ${{ inputs.javaversion }}
          distribution: corretto
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # ratchet:gradle/actions/setup-gradle@v6.1.0
        env:
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath # Eksluderer test dependencies
        with:
          dependency-graph: generate-and-submit
      - name: Build
        run: ./gradlew ${{ inputs.buildcommand }}
        env:
          GITHUB_TOKEN: ${{ (inputs.readertoken && secrets.READER_TOKEN) || secrets.GITHUB_TOKEN }}
      - uses: nais/docker-build-push@be85229e81c0293c265c646c084f05317fb6e0d2 # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: ${{ inputs.team }}
          push_image: true
          tag: latest
          pull: true
          dockerfile: Dockerfile
          docker_context: ${{ inputs.dockercontext }}
