name: Build
on:
  workflow_call:
    inputs:
      team:
        required: true
        type: string
        default: omsorgspenger
      dockercontext:
        required: false
        type: string
        default: .
      readertoken:
        required: false
        type: boolean
        default: false
      buildcommand:
        required: false
        type: string
        default: --configuration-cache build shadowjar -x test
      javaversion:
        required: false
        type: string
        default: '21'
      scan-sensitive-data:
        required: false
        type: boolean
        default: true
        description: "Skal sensitiv data scan kjøres?"
    outputs:
      image:
        value: ${{ jobs.build.outputs.image }}
jobs:
  sif-code-scan:
    if: ${{ inputs.scan-sensitive-data }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
      - uses: navikt/sif-gha-workflows/.github/actions/sif-code-scan@main
  build:
    permissions:
      contents: write # for dependency submission
      id-token: write # for nais/docker-build-push
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
      - uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # ratchet:gradle/actions/wrapper-validation@v6.3.0
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # ratchet:actions/setup-java@v6.0.0
        with:
          java-version: ${{ inputs.javaversion }}
          distribution: corretto
      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # ratchet:gradle/actions/setup-gradle@v6.3.0
        env:
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath # Eksluderer test dependencies
        with:
          dependency-graph: generate-and-submit
      - name: Build
        run: ./gradlew ${{ inputs.buildcommand }}
        env:
          GITHUB_TOKEN: ${{ (inputs.readertoken && secrets.READER_TOKEN) || secrets.GITHUB_TOKEN }}
      - uses: nais/docker-build-push@0e73849f69ff260ee27597553c0a7848ca4e9795 # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: ${{ inputs.team }}
          push_image: true
          tag: latest
          pull: true
          dockerfile: Dockerfile
          docker_context: ${{ inputs.dockercontext }}
