name: Bygg pull request
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Oslo
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # ratchet:actions/checkout@v3
      - uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # ratchet:actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # ratchet:docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: nais/login@104bca34b70d1d00fe837bcd0689633978eca744 # For fetching images from Google Artifact Registry ratchet:nais/login@v0
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: k9saksbehandling
      - name: Setup database og vtp
        shell: bash
        run: |
          echo "STACK_CREATED=false" >> $GITHUB_ENV
          echo "TIMESTAMP=$(expr $(date +%Y%m%d%H%M%S))" >> $GITHUB_ENV
          echo "Oppretter dummy keystore for testing"

          (cd dev/keystore && sh ./make-dummy-keystore.sh)
          (cd dev && docker-compose -f docker-compose.yml up --quiet-pull --detach)
      - name: Venter på stacken og sjekker status
        shell: bash
        run: |
          echo "STACK_CREATED=true" >> $GITHUB_ENV
          docker ps -a
          echo
          echo "Tester om VTP er oppe"
          timeout 180 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8060/rest/isReady)" != "200" ]]; do sleep 2; done' || false
          echo Oppe!
          echo
      - name: Create settings.xml
        uses: whelk-io/maven-settings-xml-action@8a613be18185c8521e1501081adad5041840f2c8 # ratchet:whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "github", "name": "github", "url": "https://maven.pkg.github.com/${{ env.GITHUB_REPOSITORY }}", "releases": { "enabled": "true" }, "snapshots": { "enabled": "${{ inputs.snapshots }}" } }]'
          servers: '[{ "id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.READER_TOKEN }}" }]'
          output_file: settings.xml
      - name: Build
        shell: bash
        run: |
          echo "Building $(echo $GITHUB_SHA | cut -c1-7)"
          mvn clean verify -e --batch-mode --settings settings.xml --file pom.xml -DtrimStackTrace=false
        env:
          DATASOURCE_PORT: 5432
      - name: Dumper logger for feilsøking
        if: always() && env.STACK_CREATED == 'true'
        run: |
          mkdir container-logs
          cd container-logs
          docker ps -a --format '{{.Names}}' | while read pod; do docker logs $pod > $pod.log 2>&1; done
      - name: Laste opp logger
        if: always() && env.STACK_CREATED == 'true'
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # ratchet:actions/upload-artifact@v3
        with:
          name: logs
          path: container-logs/
