name: Check and pin versions in workflows with Ratchet
on:
  pull_request:
    types: [ opened, synchronize ]
    paths:
      - '.github/workflows/**'
jobs:
  ratchet:
    if: github.actor != 'dependabot[bot]'
    permissions: 
      pull-requests: read
      contents: write
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1 # Fails if more than 1 job tries to push at the same time
      fail-fast: false
      matrix:
        asset: [
          codeql-analysis.yml,
          codeql.yml,
          gradle-build.yml,
          gradle-codeql.yml,
          gradle-dependency-submission.yml,
          gradle-deploy.yml,
          gradle-sonar.yml,
          maven-dependency-submission.yml,
          package-cleaner.yml,
          trivy-pin-versions.yml,
          trivy.yml
        ]
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.head_ref }}
      - name: Check if ${{matrix.asset}} is pinned
        uses: 'docker://ghcr.io/sethvargo/ratchet@sha256:e5b2409be0d1c82c71a6e60c49027e539f4c90636529e4f8b5c25a68b68a36d4'
        with:
          args: 'check .github/workflows/${{matrix.asset}}'
          entrypoint: /ratchet
      - name: Updating pinned versions in ${{matrix.asset}}
        if: ${{ failure() }}
        uses: 'docker://ghcr.io/sethvargo/ratchet@sha256:e5b2409be0d1c82c71a6e60c49027e539f4c90636529e4f8b5c25a68b68a36d4'
        with:
          args: 'pin .github/workflows/${{matrix.asset}}'
          entrypoint: /ratchet
      - name: Commit & Push changes
        if: ${{ failure() }}
        uses: actions-js/push@156f2b10c3aa000c44dbe75ea7018f32ae999772
        with:
          github_token: ${{ secrets.RATCHET_PAT }}
          branch: ${{ github.head_ref }}
          message: Pinning versions in ${{matrix.asset}}
