name: Tester saksbehandling (reusable)
on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: 'Docker tag (from repository)'
        required: true
      frontend_only:
        type: string
        description: 'Kun kjør frontend tester'
        required: false
        default: 'false'
    outputs:
      pleiepenger: 
            description: "Utfall fra pleiepenger-test"
            value: ${{ jobs.run_tests.outputs.pleiepenger }}
      livetssluttfase:
            description: "Utfall fra livetssluttfase-test"
            value: ${{ jobs.run_tests.outputs.livetssluttfase }}
      annet:
            description: "Utfall fra annet-test"
            value: ${{ jobs.run_tests.outputs.annet }}
      frontend: 
            description: "Utfall fra frontend-test"
            value: ${{ jobs.run_frontend_tests.outputs.frontend }}

jobs:
  run_tests:
    name: Tests
    runs-on: ubuntu-latest-8-cores
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        suite: [pleiepenger, livetssluttfase, annet]
    outputs:
      pleiepenger: ${{ steps.pleiepenger.outputs.test_result }}
      livetssluttfase: ${{ steps.livetssluttfase.outputs.test_result }}
      annet: ${{ steps.annet.outputs.test_result }}
    steps:
      - uses: navikt/sif-gha-workflows/.github/actions/maven/verdikjede-test@main
        id: pleiepenger
        if: contains(matrix.suite, 'pleiepenger') && inputs.frontend_only == 'false'
        with:
          apps: 'k9-sak k9-formidling'
          test_suite: pleiepenger
          test_groups: "-Dgroups=pleiepenger '-Dtest=!PleiepengerLoggTest'"
          log_groups: "-Dgroups=etter-pleiepenger"
          # Composite actions arver ikke secrets så vi må få dem in som input
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reader-token: ${{ secrets.READER_TOKEN }}
          nais-management-project-id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          nais-workload-identity-provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: navikt/sif-gha-workflows/.github/actions/maven/verdikjede-test@main
        id: livetssluttfase
        if: contains(matrix.suite, 'livetssluttfase') && inputs.frontend_only == 'false'
        with:
          apps: 'k9-sak k9-formidling'
          test_suite: livetssluttfase
          test_groups: "-Dgroups=livetssluttfase"
          log_groups: "-Dgroups=etter-livetssluttfase"
          # Composite actions arver ikke secrets så vi må få dem in som input
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reader-token: ${{ secrets.READER_TOKEN }}
          nais-management-project-id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          nais-workload-identity-provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: navikt/sif-gha-workflows/.github/actions/maven/verdikjede-test@main
        id: annet
        if: contains(matrix.suite, 'annet') && inputs.frontend_only == 'false'
        with:
          apps: 'k9-sak k9-formidling'
          test_suite: annet
          test_groups: "-DexcludedGroups=frontendtest,frontendtest-los,pleiepenger,livetssluttfase,klage,tilbakekreving,etter-frontendtest,etter-pleiepenger,etter-livetssluttfase,etter-tilbakekreving,etter"
          log_groups: "-Dgroups=etter"
          # Composite actions arver ikke secrets så vi må få dem in som input
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reader-token: ${{ secrets.READER_TOKEN }}
          nais-management-project-id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          nais-workload-identity-provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  run_frontend_tests:
    name: Frontend Tests
    runs-on: ubuntu-latest-8-cores
    timeout-minutes: 30
    outputs:
      frontend: ${{ steps.test.outputs.test_result }}
    steps:
      - uses: navikt/sif-gha-workflows/.github/actions/maven/verdikjede-frontend-test@main
        id: test
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reader-token: ${{ secrets.READER_TOKEN }}
          nais-management-project-id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          nais-workload-identity-provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  slack:
    name: Sender slack melding
    if: ${{ always() && !cancelled() }}
    needs: [run_tests, run_frontend_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Bygger opp slack melding
        run: |
          pleiepenger=$([ "${{ inputs.frontend_only }}" == 'true' ] && echo 'skipped' || echo "${{ needs.run_tests.outputs.pleiepenger }}")
          livetssluttfase=$([ "${{ inputs.frontend_only }}" == 'true' ] && echo 'skipped' || echo "${{ needs.run_tests.outputs.livetssluttfase }}")
          annet=$([ "${{ inputs.frontend_only }}" == 'true' ] && echo 'skipped' || echo "${{ needs.run_tests.outputs.annet }}")
          frontend=${{ needs.run_frontend_tests.outputs.frontend }}
  
          title="Verdikjede er "
          all_success=true

          test_results=("$pleiepenger" "$livetssluttfase" "$annet" "$frontend")
          for result in "${test_results[@]}"; do
            if [[ "$result" != 'success' && "$result" != 'skipped' ]]; then
              all_success=false
              break
            fi
          done
  
          if [[ "$all_success" == true ]]; then
            title+="kjørt UTEN feil :rocket:"
          else
            title+="brukket :boom:"
          fi
  
          echo "SLACK_TITLE=$title" >> $GITHUB_ENV
  
          function echoStatus() {
            if [[ "$2" == 'success' ]]; then
              echo ":heavy_check_mark:  $1"
            elif [[ "$2" == 'skipped' ]]; then
              return
            else
              echo ":x:  $1"
            fi
          }
  
          echo 'SLACK_MESSAGE<<\n' >> $GITHUB_ENV
          echoStatus "Pleiepenger" $pleiepenger >> $GITHUB_ENV
          echoStatus "Livets sluttfase" $livetssluttfase >> $GITHUB_ENV
          echoStatus "Frontend" $frontend >> $GITHUB_ENV
          echoStatus "Omsorgspenger og annet" $annet >> $GITHUB_ENV
          echo '*Actor*: ${{ github.actor }}' >> $GITHUB_ENV
          echo '*Trigger*: ${{ github.repository }}:${{ inputs.tag }}' >> $GITHUB_ENV
          echo '*Trigger action*: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Trigger action ${{ github.run_id }}>' >> $GITHUB_ENV
          echo '\n' >> $GITHUB_ENV
        # https://api.slack.com/block-kit
      - name: Slack Notification
        run: >
          curl -X POST
          -H 'Content-type: application/json'
          --data '{"blocks": [
            {
              "type": "header",
              "text": {"type": "plain_text", "text": "${{ env.SLACK_TITLE }}"}
            },
            {
              "type": "section",
              "text": {"type": "mrkdwn", "text": "${{ env.SLACK_MESSAGE }}"}
            }
          ]}'
          ${{ secrets.SLACKBOT_WEBHOOK }}
