name: Tester saksbehandling - v3 (reusable)
on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: 'Docker tag (from repository) - deprecated, use image_version'
        required: true
      suites:
        type: string
        description: 'komma-separert liste med test-suiter som skal kjøres (default alle): pleiepenger, annet, klage, tilbake, frontend, frontend-los, ung, beregning, pleiepenger-samtidiguttak, pleiepenger-pleietrengende, pleiepenger-soker.'
        required: false
        default: "pleiepenger,livetssluttfase,annet,klage,tilbake,frontend,frontend-los,beregning,pleiepenger-samtidiguttak,pleiepenger-pleietrengende,pleiepenger-soker"
      override_image_artifact_name:
        type: string
        required: false
        description: 'Artifact name of docker image to download and load.'
      image_version:
        type: string
        required: true
        description: 'Version/tag of image. '
      k9-verdikjede-sha:
        type: string
        required: false
        default: 'master'
        description: 'branch, tag or sha of k9-verdikjede to checkout'
    outputs:
      pleiepenger-pleietrengende:
        description: "Utfall fra pleiepenger-pleietrengende-test"
        value: ${{ jobs.run_tests.outputs.pleiepenger-pleietrengende }}
      pleiepenger-soker:
        description: "Utfall fra pleiepenger-soker-test"
        value: ${{ jobs.run_tests.outputs.pleiepenger-soker }}
      pleiepenger-samtidiguttak:
        description: "Utfall fra pleiepenger-samtidiguttak-test"
        value: ${{ jobs.run_tests.outputs.pleiepenger-samtidiguttak }}
      beregning:
        description: "Utfall fra beregning-test"
        value: ${{ jobs.run_tests.outputs.beregning }}
      pleiepenger:
        description: "Utfall fra pleiepenger-test"
        value: ${{ jobs.run_tests.outputs.pleiepenger }}
      livetssluttfase:
        description: "Utfall fra livetssluttfase-test"
        value: ${{ jobs.run_tests.outputs.livetssluttfase }}
      annet:
        description: "Utfall fra annet-test"
        value: ${{ jobs.run_tests.outputs.annet }}
      frontend:
        description: "Utfall fra frontend-test"
        value: ${{ jobs.run_tests.outputs.frontend }}
      klage:
        description: "Utfall fra klage-test"
        value: ${{ jobs.run_tests.outputs.klage }}
      tilbake:
        description: "Utfall fra tilbake-test"
        value: ${{ jobs.run_tests.outputs.tilbake }}
      frontend-los:
        description: "Utfall fra frontend-test"
        value: ${{ jobs.run_tests.outputs.frontend-los }}
      ung:
        description: "Utfall fra ungdomsytelse-test"
        value: ${{ jobs.run_tests.outputs.ung }}

jobs:
  filter_suites:
    name: Avgjør testsuiter som skal kjøres
    runs-on: ubuntu-latest
    outputs:
      active_suites: ${{ steps.filter.outputs.filtered || '[]' }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'navikt/sif-gha-workflows'
          ref: verdikjede-test-v3
          token: ${{ secrets.READER_TOKEN }}
      
      - id: read-config
        run: |
          config=$(cat .github/config/test-suites.json | jq -c .)
          echo "config=$config" >> $GITHUB_OUTPUT
      
      - uses: navikt/sif-gha-workflows/.github/actions/filter/suites@verdikjede-test-v3
        id: filter
        with:
          suites: ${{ inputs.suites }}
          suites-config: ${{ steps.read-config.outputs.config }}

  prepare_parallel_runners:
    name: Konfigurer parallelle test-kjøringer
    runs-on: ubuntu-latest
    needs: filter_suites
    outputs:
      matrix_config: ${{ steps.prepare-matrix.outputs.config }}
    steps:
      - id: prepare-matrix
        run: |
          suites='${{ needs.filter_suites.outputs.active_suites }}'
          matrix_config=$(echo "$suites" | jq -c '[.[] | 
            if (.suite | contains("frontend")) then
              [1,2,3,4] | map({
                "suite": .,
                "shard": .,
                "name": (.suite + " (shard " + (.|tostring) + "/4)")
              })
            else
              [{"suite": ., "shard": 1, "name": .suite}]
            end
          ] | add')
          echo "config=$matrix_config" >> $GITHUB_OUTPUT

  run_tests:
    name: ${{ matrix.name }}
    runs-on: ${{ (github.ref_name == github.event.repository.default_branch && 'ubuntu-latest-8-cores' || 'ubuntu-latest-4-cores') }}
    needs: [filter_suites, prepare_parallel_runners]
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare_parallel_runners.outputs.matrix_config) }}
    outputs:
      matrix-results: ${{ steps.collect-results.outputs.results }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'navikt/k9-verdikjede'
          ref: ${{ inputs.k9-verdikjede-sha }}
          token: ${{ secrets.READER_TOKEN }}

      # Setup Java environment
      - uses: navikt/sif-gha-workflows/.github/actions/java/setup@verdikjede-test-v3

      # Setup frontend environment if needed
      - uses: navikt/sif-gha-workflows/.github/actions/frontend/setup@verdikjede-test-v3
        id: frontend-setup
        if: contains(matrix.suites.suite, 'frontend')
        with:
          node-version: '22'

      # Setup Docker environment
      - uses: navikt/sif-gha-workflows/.github/actions/docker/setup@verdikjede-test-v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          override_image_artifact_name: ${{ inputs.override_image_artifact_name }}

      # Setup and verify test stack
      - uses: navikt/sif-gha-workflows/.github/actions/stack/setup@verdikjede-test-v3
        with:
          docker_compose_f: ${{ matrix.suites.docker_compose_f }}
          image_version: ${{ inputs.image_version }}
          test_suite: ${{ matrix.suites.suite }}

      # Run tests and log checks
      - uses: navikt/sif-gha-workflows/.github/actions/test/run@verdikjede-test-v3
        id: test-run
        with:
          test_groups: ${{ matrix.suite.test_groups }}
          log_groups: ${{ matrix.suite.log_groups }}
          reader-token: ${{ secrets.READER_TOKEN }}
          timeout_test_increase: ${{ github.ref_name != github.event.repository.default_branch && '60' || '0' }}
          playwright_shard: ${{ contains(matrix.suite.suite, 'frontend') && format('{0}/4', matrix.shard) || '' }}

      # Collect results in a format suitable for the matrix
      - id: collect-results
        if: always() && !cancelled()
        run: |
          suite="${{ matrix.suite.suite }}"
          result="${{ steps.test-run.outputs.test_result }}"
          if [[ "$suite" == *"frontend"* ]]; then
            echo "results={\"${suite}_shard${{ matrix.shard }}\":\"$result\"}" >> $GITHUB_OUTPUT
          else
            echo "results={\"${suite}\":\"$result\"}" >> $GITHUB_OUTPUT
          fi

  aggregate_results:
    name: Aggregate Results
    needs: run_tests
    runs-on: ubuntu-latest
    outputs:
      pleiepenger: ${{ steps.aggregate.outputs.pleiepenger }}
      klage: ${{ steps.aggregate.outputs.klage }}
      livetssluttfase: ${{ steps.aggregate.outputs.livetssluttfase }}
      annet: ${{ steps.aggregate.outputs.annet }}
      tilbake: ${{ steps.aggregate.outputs.tilbake }}
      frontend: ${{ steps.aggregate.outputs.frontend }}
      frontend-los: ${{ steps.aggregate.outputs.frontend-los }}
      ung: ${{ steps.aggregate.outputs.ung }}
      beregning: ${{ steps.aggregate.outputs.beregning }}
      pleiepenger-samtidiguttak: ${{ steps.aggregate.outputs.pleiepenger-samtidiguttak }}
      pleiepenger-pleietrengende: ${{ steps.aggregate.outputs.pleiepenger-pleietrengende }}
      pleiepenger-soker: ${{ steps.aggregate.outputs.pleiepenger-soker }}
    steps:
      - id: aggregate
        run: |
          results='{}'
          for result in ${{ toJSON(needs.run_tests.outputs.matrix-results) }}; do
            results=$(echo "$results $result" | jq -s add)
          done
          
          # Combine frontend shard results
          frontend_success=true
          frontend_los_success=true
          
          for i in {1..4}; do
            if [[ "$(echo "$results" | jq -r ".frontend_shard${i} // \"success\"")" != "success" ]]; then
              frontend_success=false
            fi
            if [[ "$(echo "$results" | jq -r ".frontend-los_shard${i} // \"success\"")" != "success" ]]; then
              frontend_los_success=false
            fi
          done
          
          # Output final results
          results=$(echo "$results" | jq -c \
            --arg frontend "$([[ "$frontend_success" == "true" ]] && echo "success" || echo "failure")" \
            --arg frontend_los "$([[ "$frontend_los_success" == "true" ]] && echo "success" || echo "failure")" \
            'del(.|select(.key|test("_shard[0-9]+$"))) + {"frontend": $frontend, "frontend-los": $frontend_los}')
          
          echo "$results" | jq -r 'to_entries | .[] | "echo \"\(.key)=\(.value)\" >> $GITHUB_OUTPUT"' | bash

      - name: Print test results
        run: |
          echo "Test Results:"
          echo "--------------"
          for output in $(echo '${{ toJSON(steps.aggregate.outputs) }}' | jq -r 'to_entries[] | select(.value != null) | "\(.key)=\(.value)"'); do
            echo "$output"
          done

